# Generated by Django 5.1 on 2024-08-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_contact_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('salary_offering', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bond_exists', models.BooleanField(default=False)),
            ],
        ),
    ]
