# Generated by Django 5.1 on 2024-08-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_hireme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hireme',
            old_name='bond_exists',
            new_name='bond',
        ),
        migrations.AddField(
            model_name='hireme',
            name='contact_no',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hireme',
            name='your_name',
            field=models.CharField(default='default_value', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hireme',
            name='company_name',
            field=models.CharField(max_length=200),
        ),
    ]
