# Generated by Django 5.1 on 2024-08-10 02:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_bond_exists_hireme_bond_hireme_contact_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hireme',
            name='bond_duration_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hireme',
            name='email_id',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hireme',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hireme',
            name='contact_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hireme',
            name='your_name',
            field=models.CharField(max_length=255),
        ),
    ]
